# Generated by Django 5.2.1 on 2025-06-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildrequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='buildrequest',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='buildrequest',
            name='region',
        ),
        migrations.RemoveField(
            model_name='buildrequest',
            name='use_case',
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='build',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='issue',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='prompt',
            field=models.TextField(default='Unknown Prompt'),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
        ),
    ]
