# Generated by Django 5.2.1 on 2025-06-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requestbuild_delete_buildrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestbuild',
            old_name='issue',
            new_name='issues',
        ),
    ]
