# Generated by Django 5.2.4 on 2025-11-11 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_issue_requestbuild_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbuild',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
